# Generated by Django 3.1.1 on 2020-11-25 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0025_auto_20201123_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='zixun',
            name='fabushijian',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
