# Generated by Django 3.1.1 on 2020-12-08 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0026_zixun_fabushijian'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifashi',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonghu',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
