# Generated by Django 3.1.1 on 2020-12-15 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0027_auto_20201208_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='mibao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mibaowenti', models.CharField(max_length=1000)),
                ('mibaodaan', models.CharField(max_length=1000)),
                ('mibaolaiyuan_id', models.CharField(max_length=1000)),
                ('shenfen', models.CharField(default='null', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='fuwu',
            name='shijian',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifadian',
            name='mima',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lifashi',
            name='mima',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tupian',
            name='tupianleixing',
            field=models.CharField(choices=[('0', '理发店'), ('1', '理发师'), ('2', '发型'), ('3', '用户'), ('4', '资讯'), ('5', '头像')], max_length=1),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='mima',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='yuyuedingdan',
            name='yijieshou',
            field=models.IntegerField(choices=[('-1', '已拒绝'), ('0', '未接受'), ('1', '已接受')]),
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('send_type', models.CharField(choices=[('0', '注册'), ('1', '找回密码')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.yonghu')),
            ],
            options={
                'unique_together': {('yonghu', 'email')},
            },
        ),
    ]
